name: fertilityshare
description: "Fertilityshare"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.1.0
  webview_flutter_web: ^0.2.3
  web: ^1.1.1
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fertilityshare.png"
  macos:
    generate: true
    image_path: "assets/images/fertilityshare.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
