name: fertilityshare
description: "Fertilityshare"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.1.1
  webview_flutter: ^4.13.1
  webview_flutter_web: ^0.2.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fertilityshare.png"
  macos:
    generate: true
    image_path: "assets/images/fertilityshare.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
